Repository kunaldhongade/Python-hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#3 issue fixed python
  02_Strings/setA/01_cntNumOfChar.py
  README.md
  extra/addition.py
Labels: hacktoberfest-accepted

#10 Create linkedlist-py.py
  linkedlist-py.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#9 Create two sum (leetcode)
  extra/two sum (leetcode)
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#8 Median of Two Sorted Arrays
  Leetcode/medianoftwosortedarrays.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#12 Added a leetcode question with solution in python
  Leetcode/3sum_closest.py
Labels: hacktoberfest-accepted, hacktoberfest

#14 Create graph.py
  graph.py
Labels: hacktoberfest-accepted, hacktoberfest

#15 Words with min and max ASCII value.py
  Words with min and max ASCII value.py.py
Labels: hacktoberfest-accepted

#17 Create Snake.py
  extra/Snake.py
Labels: good first issue, hacktoberfest-accepted

#20 Added Simple Calculator
  01_BasicPython/simplecalc.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#19 Create calculator_gui.py
  extra/calculator_gui.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#18 Program to find perfect number
  extra/Perfectnumber.py
Labels: good first issue, hacktoberfest-accepted, hacktoberfest
